"""add knowledge graph tables

Revision ID: a46188834f8a
Revises: 197a11807460
Create Date: 2026-07-28 09:26:50.316269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a46188834f8a'
down_revision: Union[str, None] = '197a11807460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kg_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'normalized_name', name='uq_kg_entity_type_norm')
    )
    with op.batch_alter_table('kg_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kg_entities_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_kg_entities_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('kg_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['kg_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'normalized_alias', name='uq_kg_alias_entity_norm')
    )
    with op.batch_alter_table('kg_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kg_aliases_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kg_aliases_normalized_alias'), ['normalized_alias'], unique=False)

    op.create_table('kg_relations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_entity_id', sa.String(length=36), nullable=False),
    sa.Column('predicate', sa.String(length=32), nullable=False),
    sa.Column('object_entity_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['object_entity_id'], ['kg_entities.id'], ),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['kg_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_entity_id', 'predicate', 'object_entity_id', name='uq_kg_relation_triple')
    )
    with op.batch_alter_table('kg_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kg_relations_object_entity_id'), ['object_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kg_relations_subject_entity_id'), ['subject_entity_id'], unique=False)

    op.create_table('kg_entity_mentions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('mention', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['kg_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'chunk_id', name='uq_kg_mention_entity_chunk')
    )
    with op.batch_alter_table('kg_entity_mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kg_entity_mentions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kg_entity_mentions_entity_id'), ['entity_id'], unique=False)

    op.create_table('kg_relation_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('relation_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('quote_hash', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relation_id'], ['kg_relations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relation_id', 'chunk_id', 'quote_hash', name='uq_kg_evidence_rel_chunk_quote')
    )
    with op.batch_alter_table('kg_relation_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kg_relation_evidence_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kg_relation_evidence_relation_id'), ['relation_id'], unique=False)

    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graph_status', sa.String(length=20), server_default='pending', nullable=False))
        batch_op.add_column(sa.Column('graph_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('graph_extracted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_column('graph_extracted_at')
        batch_op.drop_column('graph_error')
        batch_op.drop_column('graph_status')

    with op.batch_alter_table('kg_relation_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kg_relation_evidence_relation_id'))
        batch_op.drop_index(batch_op.f('ix_kg_relation_evidence_document_id'))

    op.drop_table('kg_relation_evidence')
    with op.batch_alter_table('kg_entity_mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kg_entity_mentions_entity_id'))
        batch_op.drop_index(batch_op.f('ix_kg_entity_mentions_document_id'))

    op.drop_table('kg_entity_mentions')
    with op.batch_alter_table('kg_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kg_relations_subject_entity_id'))
        batch_op.drop_index(batch_op.f('ix_kg_relations_object_entity_id'))

    op.drop_table('kg_relations')
    with op.batch_alter_table('kg_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kg_aliases_normalized_alias'))
        batch_op.drop_index(batch_op.f('ix_kg_aliases_entity_id'))

    op.drop_table('kg_aliases')
    with op.batch_alter_table('kg_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kg_entities_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_kg_entities_entity_type'))

    op.drop_table('kg_entities')
    # ### end Alembic commands ###
